---
language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev

services:
  - docker

before_install:
  - ./.travis/preinstall

install:
  - pip install tox tox-travis

script:
  - ./.travis/runtox
