# SPDX-License-Identifier: MIT
---
dist: xenial
language: python
env:
  global:
    - LSR_ANSIBLES='ansible==2.7.* ansible==2.8.* ansible==2.9.*'
    - LSR_MSCENARIOS='default'
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.8-dev

services:
  - docker

before_install:
  - ./.travis/preinstall

install:
  - pip install tox tox-travis

script:
  - ./.travis/runtox
