---
dist: xenial
language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.6
      env: aptpkgs=python3-selinux
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev
    # - python: nightly

services:
  - docker

before_install:
  - if [ -n "${aptpkgs}" ]; then sudo apt-get install -y python3-selinux; fi

install:
  - pip install tox tox-travis

script:
  - tox
